### PR TITLE
MAKER-432 lsz tools missing some cygwin dlls

### PR DESCRIPTION
**Pull request by bigdinotech**
Some of the cygwin dlls we removed because it worked without it in 1.6.0
is actually needed to work in 1.6.x-core-installer

### CODE REVIEW

**Comment by bigdinotech** [comment]
@manoelramonintel ready for review

**Comment by manoelramonintel** [comment]
this is really odd because these dll are part of root dir in the IDE. Could you check if your IDE contains such files in the base directory ? Otherwise you need to run "ant dist" to make sure you have all files you need.

**Comment by bigdinotech** [comment]
1.6.x-core-installer does not have the dlls on the IDE root folder

**Comment by manoelramonintel** [comment]
show me in the office

**Comment by manoelramonintel** [comment]
@calvinatintel ready for cherry-pick

**Pull request merged**
