### PR TITLE
Open source cleanup and add DFU-Util README

### PR DESCRIPTION
**Pull request by bbaltz505**
Delete clupload files for Edison/Galileo and unused lsz, libusb and Bash files

### CODE REVIEW

**Comment by bbaltz505** [comment]
@SidLeung @calvinatintel this is for issue #45 . Also there is no need for Galileo/Edison upload scripts in clupload anymore, yes? Cleaning up lsz and other obsolete files.

**Comment by bigdinotech** [comment]
@bbaltz505  Doesn't Edison and Galileo use the same repo?

**Comment by calvinatintel** [comment]
@bbaltz505 Did you mean to delete the files from arduino101load branch? IIRC, windows/linux64/linux32/osx branches are used by Galileo and Edison.

**Comment by bbaltz505** [comment]
Yes. Sorry, I thought they had their own repo for some reason. I'll add the Bash, cygwin and clupload files back.

**Comment by bbaltz505** [comment]
@bigdinotech @calvinatintel Just added the dfu-util README

**Comment by bbaltz505** [comment]
@calvinatintel ready for review

**Pull request merged**
