### PR TITLE
Sign all exe files in arduino tool. Signature is valid till 2019

### PR DESCRIPTION
**Pull request by yashaswini-hanji**
@calvinatintel @noelpaz  exe is signed with latest key. Please test it.

### CODE REVIEW

**Comment by calvinatintel** [comment]
Can you sign all relevant `.exe`s in one commit?

**Comment by yashaswini-hanji** [comment]
@calvinatintel ,  As per repo history https://github.com/01org/intel-arduino-tools/commits?author=calvinatintel only 3 cat(intc_composite.cat, intc_libusb.cat, intc_serial.cat) files and 1 exe (arduino101load.exe) file signed so far. Also I do not see digital signature in many exe(bash.exe, lsz.exe etc) file properties. 

dpinst-amd64.exe and dpinst-x86.exe singed in 2009 and never updated. 

This time should i sign all these exe's and make single commit. Please let me know.

**Comment by yashaswini-hanji** [comment]
@calvinatintel @noelpaz All exe files are signed. Please review it.

**Comment by calvinatintel** [comment]
Can you please update the PR title?

**Review by calvinatintel — COMMENTED** [review]
Certs look good. @noelpaz would you please run this through testing? Since it touches `bash.exe` and `lsz.exe`, a complete test would include Galileo and Edison.

**Comment by yashaswini-hanji** [comment]
PR tittle is updated.

**Comment by noelpaz** [comment]
Certificate for arduino101load.exe  As seen by Windows cert mamanger. Cert expiration verified

image

**Review by noelpaz — APPROVED** [review]
I validated that all the certificates for exes  in the tool directory are expiring on 2/2/2019. I also ran a BAT test and we have no issues.

**Comment by noelpaz** [comment]
@russmcinnis  is running testing on Galileo and Edison

**Comment by russmcinnis** [comment]
We uploaded Edison with this PR and there were no issues. Noel and I loaded the corelibs for Curie and then copied the bin directory to the Intel (Edison) bin directory.

**Review by calvinatintel — APPROVED** [review]

**Comment by yashaswini-hanji** [comment]
Changes are merged. Thanks for the review.

**Pull request merged**
