### PR TITLE
ATLEDGE-464 SketchUpload recognizes Windows paths with spaces

### PR DESCRIPTION
**Pull request by bbaltz505**
Original issue was found in Win XP. Verified fix on Win 7 system with username containing a space (Brian Baltz).

### CODE REVIEW

**Comment by bbaltz505** [comment]
@calvinatintel @kmsywula please review

**Comment by kmsywula** [comment]
@bbaltz505 
Brian, I reworked the script slightly to handle verbose/quiet options. Would you recheck if the problem persists?
https://github.com/01org/intel-arduino-tools/pull/21

**Comment by bbaltz505** [comment]
@kmsywula I tested the script with my modifications added to your PR (21) and it worked fine. I'll rebase my PR once your PR is merged.

**Comment by calvinatintel** [comment]
@bbaltz505 Krzysztof's changes are in

**Comment by bbaltz505** [comment]
Rebased onto latest HEAD. Will test tomorrow on a Windows VM I have configured for this error.

**Comment by bbaltz505** [comment]
Updated script works fine on Win7 with username containing a space (e.g., Arduino dir = "\users\Test User\AppData\Local\Arduino15".

@kmsywula @calvinatintel please review

**Comment by SidLeung** [comment]
@calvinatintel Please merge the changes.  Will ask Noel to test it.

**Pull request merged**
